-- *********************************** SqlDBM: Snowflake **********************************
-- * Generated by SqlDBM: Other testing [--], v2 by alexey.alferov+view.impact@sqldbm.com *


CREATE FILE FORMAT CsvFileFormat
 TYPE = CSV
 COMPRESSION = BROTLI;
