-- *********************************** SqlDBM: Snowflake **********************************
-- * Generated by SqlDBM: Other testing [--], v2 by alexey.alferov+view.impact@sqldbm.com *


-- ************************************** Dim_Product
CREATE TABLE Dim_Product
(
 ProductId      int NOT NULL,
 ProductName    string NOT NULL,
 IsDiscontinued boolean NOT NULL,
 CONSTRAINT PK_Product PRIMARY KEY ( ProductId )
)
STAGE_FILE_FORMAT = 
(
 TYPE = JSON
);
